Feat/score pub dev
moneytrackio/tezart pull request #33
Opened 2021-03-14 18:55 UTC by bwnyasse

2021-03-15 09:31 UTC, elkesrio requested changes

2021-03-15 09:31 UTC, elkesrio commented on .github/workflows/test.yml
> +        echo "the pana score is ${{ env.SCORE }}/100" && exit 1
Il me semble que le score est / 110

2021-03-15 09:31 UTC, elkesrio commented on .github/workflows/test.yml
> +        echo "the pana score is ${{ env.SCORE }}/100" && exit 1
Je mettrais ces deux jobs dans le même job

2021-03-15 09:31 UTC, elkesrio commented on tool/tezart
> +	log::info "pub.dev Score is $score/100"
```suggestion
	log::info "pub.dev Score is $score/110"
```

2021-03-15 09:31 UTC, elkesrio commented on tool/tezart
> +	dart2native tool/pana-output-parser.dart -o tool/pana-output-parser
je ne suis pas sûr de comprendre ton commentaire. Dans la CI on a déjà dart d'installé, autant lancer directement `tool/pana-output-parser.dart` et virer cette ligne. Non ?

2021-03-18 08:34 UTC, elkesrio requested changes

2021-03-18 08:34 UTC, elkesrio commented on .github/workflows/test.yml
> +        echo "the pana score is ${{ env.SCORE }}/100" && exit 1
@bwnyasse up!

2021-03-19 00:09 UTC, bwnyasse commented on .github/workflows/test.yml
> +        echo "the pana score is ${{ env.SCORE }}/100" && exit 1
@elkesrio  je repousse , je merge les 2 jobs oui

2021-03-19 09:04 UTC, elkesrio approved these changes

2021-03-19 14:53 UTC, merged