feat(mergify): setup mergify
moneytrackio/tezart pull request #35
Opened 2021-03-21 20:19 UTC by bwnyasse

2021-03-21 20:21 UTC, bwnyasse commented
@elkesrio  J'ai init mergify , mais je n'avais pas les droits admin sur le repo pour le mettre en place. L'admin du repo doit avoir reçu une demande qu'il doit autoriser. 
Sinon j'ai quand même initialisé le fichier `.github/mergify` que je te laisse revoir.

2021-03-22 09:40 UTC, elkesrio requested changes

2021-03-22 09:40 UTC, elkesrio commented on .github/mergify.yml
> +  - name: automatic merge for master when Github Action Run tests passes with at least 1 review and not WIP
je ne suis pas sûr qu'on veuille ça. À moins que j'aie mal compris. 

Ce job va merge une PR automatiquement si elle a un approve, qu'elle passe les tests et qu'elle n'est pas en WIP?

C'est trop dangereux je trouve, je préfère laisser cette partie manuelle pour plus de contrôles

2021-03-22 09:40 UTC, elkesrio commented on .github/mergify.yml
> +  - name: remove outdated reviews
Une review peut rester d'actualité même si la PR a été màj. Les reviews vont, de toute façon, être résolues avant le merge

2021-03-22 09:40 UTC, elkesrio commented on .github/mergify.yml
> +  - name: merge when all requested reviews are valid
Idem que le 1er commentaire

2021-03-22 09:40 UTC, elkesrio commented on .github/mergify.yml
> +
La carte JIRA est mal spécifiée, mais son objectif est d'avoir une queue de merges : https://docs.mergify.io/actions/queue.html

2021-03-22 16:53 UTC, akettal commented on .github/mergify.yml
> +      - author!=@myorg/regularcontributors
La doc est pas claire, mais je crois que @myorg est un placeholder (cf https://docs.mergify.io/examples.html?highlight=myorg#id18).

```suggestion
      - author!=@moneytrack/regularcontributors
```

2021-03-26 13:30 UTC, bwnyasse commented on .github/mergify.yml
> +      - "#approved-reviews-by>=2"
@elkesrio  si on met un label urgent, Mergify le met en priorité. Pour ce use case ,  j'ai laissé 2 reviewers obligatoire pour que le merge passe dans la branche `main`

2021-03-26 13:31 UTC, bwnyasse commented on .github/mergify.yml
> +      - "#approved-reviews-by>=1"
@elkesrio  pour les autres par défaut , on peut continuer avec le fonctionnement actuel  , à savoir 1 seul reviewer suffira

2021-03-31 09:20 UTC, elkesrio requested changes

2021-03-31 09:20 UTC, elkesrio commented on .github/mergify.yml
> +      - "#approved-reviews-by>=2"
Je ne pense pas qu'on ait besoin d'une queue urgente, on ne sera pas plus de 3 développeurs sur le projet. Autant simplifier avec une seule queue

2021-03-31 09:20 UTC, elkesrio commented on .github/mergify.yml
> +      - "#approved-reviews-by>=1"
Je me demande si on veut mettre la règle du nombre d'approvers dans mergify aussi? C'est peut-être suffisant de faire cette règle dans les settings du projet ? 🤔

2021-03-31 09:20 UTC, elkesrio commented on .github/mergify.yml
> +  - name: ask to resolve conflict
C'est pas un peu redondant ça ? Github nous informe déjà quand il y a des conflits !

2021-04-04 14:51 UTC, bwnyasse commented on .github/mergify.yml
> +  - name: ask to resolve conflict
@elkesrio je ne suis pas que ce soit exactement redondant avec celui de `mergify`. Github nous informe qu'il ya conflits. Mais comme je n'ai jamais utilisé mergify, je ne sais pas comment Github se comporte avec les conflits dans la `merge queue`. Je te propose qu'on laisse ça , et on analysera le comportement . Et si c'est inutile, on supprimera

2021-04-06 08:14 UTC, elkesrio approved these changes

2021-04-06 08:14 UTC, merged