Feat/contract deployment impl
moneytrackio/tezart pull request #37
Opened 2021-03-22 16:04 UTC by glavigno

2021-03-22 17:45 UTC, elkesrio requested changes

2021-03-22 17:45 UTC, elkesrio commented on lib/src/core/client/impl/tezart_client.dart
> +    final counter = await rpcInterface.counter(source.address) + 1;
- il faudrait wrapper cette méthode d'un `_catchHttpError` et d'un `_retryOnCounterError`
- Pour être cohérent avec les autres méthodes, il faudrait sortir le monitoring de la méthode et retourner le résultat de l'injection (l'operation id). Le refacto de la classe `Operation` permettra de retourner plus d'informations sur la transaction

2021-03-22 17:50 UTC, Pierre-Michard commented on lib/src/core/client/impl/tezart_client.dart
> +    await rpcInterface.monitorOperation(operationId: operationId);
le monitorOperation devrait être optionnel, et avec en paramètre le nombre de confirmations (0 si on veut juste attendre que ça soit dans un bloc, plus sion veut).

2021-03-22 17:51 UTC, Pierre-Michard approved these changes

2021-03-23 09:38 UTC, elkesrio approved these changes

2021-03-23 10:00 UTC, merged