feat(edesk): implements edesk prefixes and pbkdf2 derivator
moneytrackio/tezart pull request #40
Opened 2021-03-23 18:03 UTC by glavigno

2021-04-02 10:13 UTC, elkesrio requested changes
👍

2021-04-02 10:13 UTC, elkesrio commented on lib/src/keystore/impl/keystore.dart
> +      if (encryptedSecretKey.length != _encryptedSecretKeyLength) {
- tu peux déplacer ce code dans une méthode `encryptedSecretKeyToSeed` et le mettre dans `crypto/impl/encrypted_secret_key_to_seed.dart` please ?
- changer `iteractionCount` et `keyLength` en `const`

2021-04-04 14:56 UTC, bwnyasse approved these changes

2021-04-04 14:58 UTC, bwnyasse approved these changes
@elkesrio  Je te laisse merger si tout te convient. pour moi rien de choquant

2021-04-06 07:33 UTC, elkesrio approved these changes

2021-04-06 07:33 UTC, merged