Refactor/encapsulate operation logic in a dedicated class
moneytrackio/tezart pull request #43
Opened 2021-03-31 15:53 UTC by elkesrio

2021-04-04 17:03 UTC, bwnyasse requested changes

2021-04-04 17:03 UTC, bwnyasse commented on example/example.dart
> +  final operationsList = await client.transferOperation(
Faudra mettre  à jour la documentation.
Je ne recupère pas de manière automatique pour le moment le fichier `example.dart` et `example_with_log.dart` pour mettre dans la section `Example` du fichier `docs/README.md` 

Peut être il nous faut une user story pour faire ça automatique ?

2021-04-06 08:20 UTC, elkesrio commented on .github/workflows/test.yml
> +        ./tezart coverage
- parce qu'en lançant `./tezart tests` et `./tezart coverage` on lance deux fois les tests (on ne le voyait pas car la lib qu'on utilisait pour le coverage n'affichait pas les logs).
- j'ai modifié `./tezart coverage` pour lancer `tezart::_check_localhost_chain`,  `tezart::_init_env_var`, `tezart::_run_build_runner`

2021-04-12 08:58 UTC, glavigno commented on lib/src/common/validators/simulation_result_validator.dart
> +    return _status == 'applied' ? true : false;
`return _status == 'applied';`

2021-04-12 09:04 UTC, glavigno approved these changes

2021-04-12 09:28 UTC, elkesrio commented on lib/src/common/validators/simulation_result_validator.dart
> +    return _status == 'applied' ? true : false;
ahaha oui effectivement 😄

2021-04-12 09:30 UTC, akettal commented on lib/src/core/client/impl/tezart_client.dart
> +      return managerKey == null ? false : true;
```suggestion
      return managerKey == null;
```

2021-04-12 09:30 UTC, akettal commented on lib/src/models/operations_list/impl/operations_list.dart
> +  void addOperation(Operation op) {
Détail : pour une question de symétrie, renommer `appendOperation` ?

2021-04-12 09:44 UTC, elkesrio commented on lib/src/core/client/impl/tezart_client.dart
> +      return managerKey == null ? false : true;
C'est plutôt 

```suggestion
      return managerKey != null;
```

2021-04-12 09:44 UTC, elkesrio commented on lib/src/models/operations_list/impl/operations_list.dart
> +  void addOperation(Operation op) {
oui bien vu

2021-04-12 09:53 UTC, akettal commented on lib/src/core/client/impl/tezart_client.dart
> +      return managerKey == null ? false : true;
👍 😅

2021-04-12 09:53 UTC, akettal approved these changes

2021-04-12 09:56 UTC, merged